# Licensed under GNU Lesser General Public License v3.0

# install: conda env create -f conda_env.yaml 
# update:  conda env update -f conda_env.yaml 

name: vidtools
dependencies:
  - python=3.8
  - pip
  - conda-forge::filterpy=1.4.5
  - conda-forge::lap=0.4.0
  - conda-forge::opencv=4.5.0
  - scikit-image
  - pyyaml
  - tqdm
  - click
  - pip:
    - motmot.FlyMovieFormat
    - ffmpy # TODO: replace with ffmpeg-python