h264_to_mp4:
  root: ~/tmp/
  framerate: 30
  do_mono: true # higher quality with opencv backend

undistort:
  board: /mnt/2TB/data_in/cashylinidae/tests/higher_arena/calib_files/calibration.mp4
  framerate: 30
  m_corners: 6
  n_corners: 7
  target: /mnt/2TB/data_in/cashylinidae/tests/higher_arena/calib_files/calibration.mp4
  do_debug: false
  do_crop: true # must be true, if the output is a checkerboard vid to be used in pxls_to_real

pxls_to_real:
  real_board_square_len: 20 # real world units, e.g. mm
  undistorted_board: /mnt/2TB/data_in/cashylinidae/tests/higher_arena/calib_files/calibration_undistorted.mp4
  framerate: 30 
  m_corners: 6
  n_corners: 7
  frames: []
  do_ask: false

find_circles:
  root: /mnt/2TB/data_in/cashylinidae/tests/higher_arena/2021-01-01
  # root: ~/tmp/test/
  dp: 2
  param1: 80
  param2: 200
  minDist: 140
  minRadius: 400
  maxRadius: 0
  frames: []
  do_ask: false