vid_to_imgs:
  # root: ~/tmp/test
  root: /mnt/2TB/data_in/cashylinidae/data/point_in_sea/
  vid_ending: _undistorted_masked.mp4
  ext: png
  frames: []
  do_ask: false
  do_overwrite: false # false

h264_to_mp4:
  root: /mnt/2TB/data_in/cashylinidae/data/one_vs_one/non_dalotia_aleos/cashy_3 # /mnt/2TB/data_in/cashylinidae/data/point_in_sea # ~/tmp/test
  framerate: 30
  do_mono: true # higher quality with opencv backend

undistort:
  # board: /mnt/2TB/data_in/cashylinidae/calib_files/cam/cashy_/calibration.mp4
  board: /mnt/2TB/data_in/cashylinidae/calib_files/cam/cashy_3/calibration.mp4
  framerate: 30
  m_corners: 6
  n_corners: 7
  # target: /mnt/2TB/data_in/cashylinidae/data/point_in_sea
  target: /mnt/2TB/data_in/cashylinidae/data/one_vs_one/non_dalotia_aleos/cashy_3
  do_debug: false
  do_crop: true # must be true, if the output is a checkerboard vid to be used in pxls_to_real

pxls_to_real:
  real_board_square_len: 20 # real world units, e.g. mm
  undistorted_board: /mnt/2TB/data_in/cashylinidae/calib_files/cam/cashy_3/calibration_undistorted.mp4
  framerate: 30 
  m_corners: 6
  n_corners: 7
  frames: []
  do_ask: false

circular_mask_crop:
  root: /mnt/2TB/data_in/cashylinidae/data/one_vs_one/non_dalotia_aleos/cashy_3
  # root: ~/tmp/test/
  vid_ending: _undistorted.mp4
  framerate: 30
  dp: 2 # 1
  param1: 80 # 30 # 28 # 80
  param2: 200 # 70 # 45 # 200
  minDist: 140
  minRadius: 400
  maxRadius: 0
  frames: [] # [0]
  do_ask: false

make_timelapse:
  root: /mnt/2TB/data_in/cashylinidae/tests/higher_arena/
  vid_ending: _undistorted.mp4
  density: 0.01
  is_dark_on_light: true

track_blobs:

  # root: ~/tmp/test/test_vids
  # root: ~/Dropbox/_mysci/datasets/toy_behav/cashy/test/interaction.mp4
  # root: ~/tmp/test_blobs
  root: /mnt/2TB/data_in/cashylinidae/data/point_in_sea
  vid_ending: _undistorted_masked.mp4
  framerate: 30
  do_show: false

  # Detector params:
  min_area: 10
  max_area: 400
  min_circularity: null
  max_circularity: null
  min_convexity: null
  max_convexity: null
  min_inertia_ratio: null
  max_inertia_ratio: null

  # SORT tracker params:
  max_age: 4 # 1
  min_hits: 0 # 1 https://github.com/abewley/sort/issues/17#issuecomment-767695435 ... maybe don't make this an arg
  iou_thresh: 0.2 # 0.2
  