vid_to_imgs:
  root: ~/tmp/test
  # root: ~/tmp/test/liomOcc_dalCor_45c_1_1_2021-01-01_undistorted.mp4
  ext: png
  frames: []
  do_ask: true

h264_to_mp4:
  root: ~/tmp/test
  framerate: 30
  do_mono: true # higher quality with opencv backend

undistort:
  board: /mnt/2TB/data_in/cashylinidae/tests/lower_arena/calib_files/calibration.mp4
  framerate: 30
  m_corners: 6
  n_corners: 7
  target: /mnt/2TB/data_in/cashylinidae/tests/lower_arena/
  do_debug: false
  do_crop: true # must be true, if the output is a checkerboard vid to be used in pxls_to_real

pxls_to_real:
  real_board_square_len: 20 # real world units, e.g. mm
  undistorted_board: /mnt/2TB/data_in/cashylinidae/tests/lower_arena/calib_files/calibration_undistorted.mp4
  framerate: 30 
  m_corners: 6
  n_corners: 7
  frames: []
  do_ask: false

find_circle:
  # root: /mnt/2TB/data_in/cashylinidae/data
  root: ~/tmp/test/
  dp: 2 # 1
  param1: 80 # 30 # 28 # 80
  param2: 200 # 70 # 45 # 200
  minDist: 140
  minRadius: 400
  maxRadius: 0
  frames: [] # [0]
  do_ask: false

track_blobs:

  # root: ~/tmp/test/test_vids
  root: ~/Dropbox/_mysci/datasets/toy_behav/cashy/test/trimmed.mp4
  framerate: 30
  do_show: false
  percent_for_bkgd: 0.1

  # Detector params:
  min_threshold: 200 # TODO: Get rid of these threshold values, bc I just need to set min to less than what I compute from my Otsu
  max_threshold: 255
  min_area: 10
  max_area: 400
  min_circularity: null
  max_circularity: null
  min_convexity: null
  max_convexity: null
  min_inertia_ratio: null
  max_inertia_ratio: null

  # SORT tracker params:
  max_age: 4 # 1
  min_hits: 0 # 1 https://github.com/abewley/sort/issues/17#issuecomment-767695435 ... maybe don't make this an arg
  iou_thresh: 0.2 # 0.2
  